[package]
name = "kiwi-ecs"
version = "1.0.0"
edition = "2021"
author = "Jonas Everaert"
license = "MIT"

[dependencies]
kiwi-internal-macros = { path = "../internal-macros" }
kiwi-macros = { path = "../macros" }
